### ISSUE TITLE
SFTP create an alternate "resources" folder when I save a file under Laravel "Modules"

### ISSUE THREAD

**Issue by danielrepos** [Natizyskunk/vscode-sftp#270]
**Do you read the FAQ?**
- [ ] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I'm using SFTP extension on VS code to view my changes directly on a server but when I save a file under Laravel "Modules", it create an alternate "resources/views" folder instead of just saving the file like my local structure (Resources/views). Bcuz of this changes doesn't reflect on browser bcuz its creating an alternate directry on save.

**To Reproduce**
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.51.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.
      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by Natizyskunk** [comment]
@danielrepos,
I'm not sure about what the problem is. Can you be more precise and add some picutres maybe ?
Also please respect the issue template available [here](https://github.com/Natizyskunk/vscode-sftp/issues/new/choose) when opening a new issue. In your case you should use the "[Bug report](https://github.com/Natizyskunk/vscode-sftp/issues/new?assignees=&labels=&template=bug_report.md&title=)" issue template.

**Comment by Natizyskunk** [comment]
Related issues : #24, #86 #110 #240
Should be fixed in the next update (v1.16.2).

**Comment by Natizyskunk** [comment]
@danielrepos,
I'm not sure about what the problem is. Can you be more precise and add some picutres maybe ?
Also please respect the issue template available [here](https://github.com/Natizyskunk/vscode-sftp/issues/new/choose) when opening a new issue. In your case you should use the "[Bug report](https://github.com/Natizyskunk/vscode-sftp/issues/new?assignees=&labels=&template=bug_report.md&title=)" issue template.
Now for this time you can simply edit and update this issue. No need to open a new one.

**Comment by Natizyskunk** [comment]
@danielrepos,
I've published a new `pre-v1.16.2` pre-release that should fix your problem. You can download it [here](https://github.com/Natizyskunk/vscode-sftp/releases/tag/pre-v1.16.2) or directly from VSCode.
![image](https://user-images.githubusercontent.com/59120131/204685005-69a0b836-cf8f-4187-ae7a-295c5ceddc72.png)
![image](https://user-images.githubusercontent.com/59120131/204685143-2c3be7cb-ecd4-450d-9bc2-90afc982b1ee.png)

**Comment by danielrepos** [comment]
Thank you very much, and I'm really sorry about the template.

**Comment by Natizyskunk** [comment]
You're welcome. No problem. Let me knoow if it fix your bug.

**Comment by matijasulc** [comment]
Hi, I have switched to Pre-Release version but it does not fix problem with filename (tesT.php was the first name, now I have renamed it to test.php and it cannot be downloaded from server or uploaded with exact that name, it always tries to download or upload tesT.php).
